name: stylegan2-ada-pytorch
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.7.1
  - cudatoolkit>=11.0  # Replace with your specific CUDA toolkit version
  - click
  - requests
  - tqdm
  - ninja
  - typer
  - pip:
    - pyspng
    - imageio-ffmpeg
